### ISSUE TITLE
[Tutorial] Running on Docker with Docker-Compose

### ISSUE THREAD

**Issue by uchihaservice** [caf203/loggerv3#43]
Hey everyone,

Here is a docker compose file.

The bot works perfectly with it. If you want to set it up quickly.

Please create the following folders
logger
bezerk

Clone logger to /logger/
Clone bezerk to /bezerz/.

After that you can run `docker-compose up -d` without any problems.
Run `node src/miscellaneous/generateDB.js` before the first start & adjust the .env.

```
version: "2"
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./cache:/data
  node:
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./logger:/home/node/app
    command: "node index.js"
    depends_on:
      - cache
      - node2
      - db
  node2:
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./bezerk:/home/node/app
    command: "node index.js"
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "YOurPassWoRd"
```
